### ISSUE TITLE
How to use the extension

### ISSUE THREAD

**Issue by axhamre** [damiensedgwick/vscode-xstate-visualizer#6]
Hi!

Sorry for a stupid question perhaps, but I don't get how to use the extension? How do I get the webview? 

Thanks in advance!

**Comment by jonboiser** [comment]
@axhamre I just had this same question. On the command pallette, look for "Visualizer". @damiensedgwick there might be something you need to do to give it a more searchable name like "XState: Open visualizer"

**Comment by damiensedgwick** [comment]
@axhamre firstly I just want to apologise as I never saw your question! I will address this asap and make it clearer going forward 👍 

Thanks for raising it as an issue.

**Comment by damiensedgwick** [comment]
Adjustments have been made to make using the extension clearer.

Thanks again.
