### ISSUE TITLE
Cannot find and import local build of React app.

### ISSUE THREAD

**Issue by damiensedgwick** [damiensedgwick/vscode-xstate-visualizer#7]
Even though I am building and outputting all JS files to the out directory, I am unable to import the local react app file for use from within a vscode webview.

```jsx
const reactAppPathOnDisk = vscode.Uri.file(
    path.join(extensionPath, "app.js") // This path is the problem I think??
);

const reactAppUri = reactAppPathOnDisk.with({ scheme: "vscode-resource" });
```

`reactAppUri` is then passed through to the html document script tag like so

```jsx
<script src="${reactAppUri}"></script>
```

From looking online, once this path is configured correct it should work however I am failing to get it working correctly. Whilst the webview does open, I hit this error:

`Error: Unable to resolve non-existing file '/Users/damienk.sedgwick/Development/vscode-xstate-visualizer/app/app.js'`

That last error stays no matter the path variations I try, I suspect this is the reason for it also returning a 404 but it could be unrelated.

**Comment by mattpocock** [comment]
Considering my code was copied from yours, this may work:

```ts
let currentPanel: vscode.WebviewPanel | undefined = undefined;

const onDiskPath = vscode.Uri.file(
  // This is the path to my file
  path.join(
    context.extensionPath,
    "client",
    "scripts",
    "webview.js",
  ),
);

const src = currentPanel.webview.asWebviewUri(onDiskPath);
currentPanel.webview.html = getWebviewContent(src);
```

**Comment by damiensedgwick** [comment]
> Considering my code was copied from yours, this may work:
> 
> ```ts
> let currentPanel: vscode.WebviewPanel | undefined = undefined;
> 
> const onDiskPath = vscode.Uri.file(
>   // This is the path to my file
>   path.join(
>     context.extensionPath,
>     "client",
>     "scripts",
>     "webview.js",
>   ),
> );
> 
> const src = currentPanel.webview.asWebviewUri(onDiskPath);
> currentPanel.webview.html = getWebviewContent(src);
> ```

Nice! Seem to be on the right path now! Now I am just dealing with processes not being defined properly. On to the next error 😂 Thanks Matt!

**Comment by mattpocock** [comment]
So hard to read up on this stuff! Google is not our friend

**Comment by damiensedgwick** [comment]
I know right! There isn't a lot of resource out there at the minute!

I think I've almost cracked it. Just got a weird module export error going on!
