### ISSUE TITLE
Webview is blank

### ISSUE THREAD

**Issue by damiensedgwick** [damiensedgwick/vscode-xstate-visualizer#8]
React app is now building and loading into the webview and although it can be seen working here: https://www.loom.com/share/97310992439244a5b9e16a3118da55b4

It is now just returning a blank screen 🤔

Needs investigating further.

**Comment by andrewmcoupe** [comment]
This is working for me after pulling the latest changes on the react embed branch 🤔

**Comment by damiensedgwick** [comment]
> This is working for me after pulling the latest changes on the react embed branch 🤔

~~oh really?? How strange... does it work every time @andrewmcoupe or is it temperamental?~~ Just tested it myself and no joy :/ this is really strange and annoying haha.
